---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-configmap
  namespace: flux-system
  labels:
    app.kubernetes.io/component: core-config
data:
  ENVIRONMENT: "EUROPE-UAT"
  TRACING_HOST:  "http://tempo.gitops-observability-system:4318/v1/traces"
  LOKI_HOST: "http://loki.gitops-observability-system:3100/loki/api/v1/push"
