---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  releaseName: loki
  interval: 1m
  chart:
    spec:
      chart: loki-stack
      version: "2.9.11"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability-system
  values:
     loki:
       enabled: true
       isDefault: false
     fluent-bit:
       enabled: false
     promtail:
       enabled: false