---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
spec:
  releaseName: tempo
  interval: 1m
  chart:
    spec:
      chart: tempo
      version: "1.7.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability-system
  values: