---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-source
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: github-secret
  url: ssh://git@github.com:malike/k8s-gitops-llm-service.git
